version: '3.7'

services:
  db:
    image: postgres
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes: 
      - ./db-bak-200427.sql:/db-bak-200427.sql
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      - test_network

  app:
    build:
      context: ./nodejs-ncdc-scraper
    depends_on:
      - db
      - cache
    environment: 
      - DATABASE_URL=postgres://postgres:password@db:5432/postgres
      - REDIS_HOST=cache
      - REDIS_PORT=6379
    networks:
      - test_network

  cache:
    image: redis
    networks:
      - test_network

  worker:
    build:
      context: ./croncvd-worker
    depends_on:
      - db
      - cache
    environment: 
      - DATABASE_URL=postgres://postgres:password@db:5432/postgres
      - REDIS_HOST=cache
      - REDIS_PORT=6379
    networks:
      - test_network

  frontend:
    build:
      context: ./ncdc-scraper-client
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - test_network
    
networks:
  test_network:
